import { useEffect, useMemo, useState } from 'react'
import { Card } from '../components/ui/Card'
import { RiskBadge } from '../components/ui/Badge'
import { LoadingState, ErrorState, EmptyState } from '../components/ui/States'
import { Icon } from '../components/ui/Icon'
import { getProjects } from '../services/projectService'
import { getRiskAssessment } from '../services/riskService'
import type { Project } from '../types'

export function ProjectPortfolioPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [projects, setProjects] = useState<Project[] | null>(null)
  const [query, setQuery] = useState('')
  const [state, setState] = useState('All states')
  const [stage, setStage] = useState('All stages')
  const [type, setType] = useState('All project types')
  useEffect(() => { getProjects().then(setProjects).catch(() => setProjects([])) }, [])
  const states = useMemo(() => ['All states', ...new Set((projects ?? []).map(project => project.state).sort())], [projects])
  const stages = useMemo(() => ['All stages', ...new Set((projects ?? []).map(project => project.acquisitionStage).sort())], [projects])
  const types = useMemo(() => ['All project types', ...new Set((projects ?? []).map(project => project.projectType).sort())], [projects])
  const filtered = useMemo(() => (projects ?? []).filter(project => (!query || `${project.id} ${project.name} ${project.state} ${project.district}`.toLowerCase().includes(query.toLowerCase())) && (state === 'All states' || project.state === state) && (stage === 'All stages' || project.acquisitionStage === stage) && (type === 'All project types' || project.projectType === type)), [projects, query, state, stage, type])
  return <div className="page"><div className="page-heading"><div><div className="title-line"><p className="eyebrow">Monitoring · Portfolio</p><span className="demo-label">DEMO DATA</span></div><h1>Land acquisition projects</h1><p className="page-subtitle">A shared project record for the dashboard, GIS workspace and future assessment services.</p></div><button className="primary-button" onClick={() => onNavigate('/projects/new')}><span>＋</span> Add project</button></div>{projects === null ? <LoadingState label="Loading project portfolio" /> : projects.length === 0 ? <Card><EmptyState title="No project records yet" message="Start a new land acquisition project to create the first record." /></Card> : <Card className="portfolio-card"><div className="portfolio-filters"><input aria-label="Search portfolio" placeholder="Search project, ID, state or district…" value={query} onChange={event => setQuery(event.target.value)} /><select aria-label="Filter portfolio state" value={state} onChange={event => setState(event.target.value)}>{states.map(option => <option key={option}>{option}</option>)}</select><select aria-label="Filter portfolio stage" value={stage} onChange={event => setStage(event.target.value)}>{stages.map(option => <option key={option}>{option}</option>)}</select><select aria-label="Filter portfolio type" value={type} onChange={event => setType(event.target.value)}>{types.map(option => <option key={option}>{option}</option>)}</select></div><div className="portfolio-note"><Icon name="database" size={16} /><span>{filtered.length} project records · Data completeness and monitoring status are separate from risk assessment.</span></div>{filtered.length === 0 ? <EmptyState title="No projects match current filters" message="Clear a filter or broaden your search." /> : <div className="table-wrap"><table><thead><tr><th>Land acquisition project</th><th>Location</th><th>Acquisition stage</th><th>Land / families</th><th>Data completeness</th><th>Monitoring status</th></tr></thead><tbody>{filtered.map(project => <tr key={project.id} onClick={() => onNavigate(`/projects/${project.id}`)} className="clickable-row"><td><div className="project-name"><strong>{project.name}</strong><small>{project.id}</small></div></td><td>{project.district}, {project.state}</td><td>{project.acquisitionStage}</td><td>{project.landArea.toLocaleString()} ha<br /><small>{project.affectedFamilies.toLocaleString()} families</small></td><td><div className="completeness-cell"><strong>{project.dataCompleteness ?? '—'}{project.dataCompleteness !== undefined && '%'}</strong><div className="mini-track"><span style={{ width: `${project.dataCompleteness ?? 0}%` }} /></div></div></td>  <td><RiskBadge level={getRiskAssessment(project).overallLevel} /><small className="score">{getRiskAssessment(project).confidence} confidence</small></td></tr>)}</tbody></table></div>}</Card>}</div>
}
