import { useEffect, useMemo, useState } from 'react'
import { Card } from '../components/ui/Card'
import { RiskBadge } from '../components/ui/Badge'
import { ErrorState, LoadingState } from '../components/ui/States'
import { getProjects } from '../services/projectService'
import { getRiskAssessment } from '../services/riskService'
import type { Project, RiskAssessment, RiskDimension } from '../types'

function RiskDimensionCard({ dimension }: { dimension: RiskDimension }) {
  const [expanded, setExpanded] = useState(false)
  return <article className="risk-dimension"><button className="risk-dimension-head" onClick={() => setExpanded(value => !value)} aria-expanded={expanded}><span><strong>{dimension.label}</strong><small>{dimension.confidence} confidence</small></span><span className="dimension-score"><RiskBadge level={dimension.level} /><b>{dimension.score === null ? '—' : dimension.score}</b><i>{expanded ? '−' : '+'}</i></span></button><div className="dimension-bar"><span className={`bar-${dimension.level.toLowerCase()}`} style={{ width: `${dimension.score ?? 0}%` }} /></div>{expanded && <div className="dimension-detail"><div><strong>Contributing factors</strong>{dimension.contributingFactors.length ? <ul>{dimension.contributingFactors.map(item => <li key={item}>{item}</li>)}</ul> : <p>No specific contributing factor recorded.</p>}</div><div><strong>Explanation</strong><p>{dimension.explanation}</p></div>{dimension.missingData.length > 0 && <div className="missing-data"><strong>Missing information</strong><p>{dimension.missingData.join(', ')}</p></div>}<small>Fields: {dimension.affectedFields.join(', ')}</small></div>}</article>
}

export function RiskPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [projects, setProjects] = useState<Project[] | null>(null)
  const [selectedId, setSelectedId] = useState('')
  const [error, setError] = useState(false)
  useEffect(() => { getProjects().then(value => { setProjects(value); setSelectedId(value[0]?.id ?? '') }).catch(() => setError(true)) }, [])
  const selected = projects?.find(project => project.id === selectedId)
  const assessment = useMemo(() => selected ? getRiskAssessment(selected) : null, [selected])
  if (error) return <div className="page"><ErrorState message="Risk assessment data could not be loaded." /></div>
  if (!projects || !assessment || !selected) return <div className="page"><LoadingState label="Evaluating structured project inputs" /></div>
  return <div className="page risk-page"><div className="page-heading"><div><div className="title-line"><p className="eyebrow">Analytics · Deterministic assessment</p><span className="demo-label">RULE-BASED · NO ML</span></div><h1>Risk intelligence</h1><p className="page-subtitle">Transparent input-based indicators for structured project records. No prediction or recommendation is generated in this phase.</p></div><select className="risk-project-select" aria-label="Select project for risk assessment" value={selectedId} onChange={event => setSelectedId(event.target.value)}>{projects.map(project => <option key={project.id} value={project.id}>{project.name} · {project.id}</option>)}</select></div><div className="assessment-meta"><span>{assessment.engineVersion}</span><span>Assessment generated {new Date(assessment.assessedAt).toLocaleString()}</span><span>Source record updated {selected.lastUpdated}</span><button className="text-button" onClick={() => onNavigate(`/projects/${selected.id}`)}>Open project record →</button></div><div className="risk-overview-grid"><Card className={`overall-assessment level-${assessment.overallLevel.toLowerCase()}`}><p className="eyebrow">Overall risk assessment</p><div className="overall-score">{assessment.overallScore === null ? '—' : assessment.overallScore}<small>{assessment.overallScore === null ? '' : '/100'}</small></div><RiskBadge level={assessment.overallLevel} /><div className="confidence-line"><span>Assessment confidence</span><strong>{assessment.confidence}</strong></div><p className="assessment-explanation">{assessment.explanation}</p></Card><Card className="drivers-card"><div className="section-heading"><div><p className="eyebrow">Input-based analysis</p><h2>Top risk drivers</h2></div></div>{assessment.topDrivers.length ? <ol>{assessment.topDrivers.map(driver => <li key={driver}>{driver}</li>)}</ol> : <p className="muted">No calculable drivers are available.</p>}<div className="notice warning">Risk drivers describe recorded project inputs. They are not ML feature importance or recommendations.</div></Card></div><Card className="dimensions-card"><div className="section-heading"><div><p className="eyebrow">Transparent breakdown</p><h2>Risk dimensions</h2></div><span className="muted">{assessment.dimensions.length} dimensions · select to expand</span></div><div className="risk-dimensions">{assessment.dimensions.map(dimension => <RiskDimensionCard key={dimension.key} dimension={dimension} />)}</div></Card>{assessment.missingData.length > 0 && <Card className="missing-card"><p className="eyebrow">Data quality boundary</p><h2>Assessment limitations</h2><p>Some dimensions have insufficient data. Missing information is not interpreted as low risk.</p><div>{assessment.missingData.map(item => <span key={item}>{item}</span>)}</div></Card>}</div>
}
